### ISSUE TITLE
Colaboração bilateral

### ISSUE THREAD

**Issue by danielramosbh74** [diegocrivelaro/scripts-py#2]
Oi Diego, tudo bem?

Só abri esta issue e a pull request para te convidar para tentarmos colaborar mutuamente um no repositório do outro, pois assim estaremos treinando de forma prática e aprendendo sem custos.

Obrigado.

**Comment by diegocrivelaro** [comment]
**Olá Daniel, estou muito bem.** 😃

Eu aceito o convite, pois é uma boa ideia para compartilhar os conhecimentos.
